# Generated by Django 2.2.1 on 2019-05-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
