# Generated by Django 2.2.1 on 2019-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_track_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='comment',
        ),
    ]
