# Generated by Django 2.2.1 on 2019-05-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_remove_track_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='end',
        ),
        migrations.RemoveField(
            model_name='track',
            name='start',
        ),
    ]
