# Generated by Django 2.2.1 on 2019-06-01 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_auto_20190601_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
